import OrdemCapa from '../assets/ordem-capa.png';
import TormentaCapa from '../assets/tormenta-capa.png';
import DedCapa from '../assets/ded-capa.png';
import CallCapa from '../assets/call-capa.png';
import { Sistema } from './types';

const dedCondicoes: Array<any> = [
    {id: 1, label: "Agarrado", value: "Agarrado", descricao: "A velocidade da criatura agarrada torna-se 0, e ela não pode se beneficiar de qualquer bônus na sua velocidade. A condição termina se o agarrador estiver incapacitado."},
    {id: 2, label: "Amedrontado", value: "Amedrontado", descricao: "A criatura amedrontada tem desvantagem em testes de habilidade e rolos de ataque enquanto a fonte de seu medo estiver à vista e não pode se mover voluntariamente para mais perto da fonte de seu medo."},
    {id: 3, label: "Atordoado", value: "Atordoado", descricao: "A criatura atordoada está incapacitada, não pode se mover e só pode falar de forma vacilante. A criatura automaticamente falha em testes de resistência de Força e Destreza."},
    {id: 4, label: "Caído", value: "Caído", descricao: "A única opção de movimento para a criatura caída é rastejar, a menos que ela se levante e termine a condição. A criatura tem desvantagem em rolos de ataque."},
    {id: 5, label: "Cego", value: "Cego", descricao: "A criatura cega não pode ver e automaticamente falha qualquer teste de habilidade que requeira visão. Os rolos de ataque contra a criatura têm vantagem, e os rolos de ataque da criatura têm desvantagem."},
    {id: 6, label: "Contido", value: "Contido", descricao: "A velocidade da criatura contida torna-se 0, e ela não pode se beneficiar de qualquer bônus na sua velocidade. Os rolos de ataque contra ela têm vantagem, e os seus rolos de ataque têm desvantagem."},
    {id: 7, label: "Encantado", value: "Encantado", descricao: "A criatura encantada não pode atacar o encantador ou alvejá-lo com habilidades ou efeitos mágicos prejudiciais. O encantador tem vantagem em qualquer teste de habilidade para interagir socialmente com a criatura."},
    {id: 8, label: "Ensurdido", value: "Ensurdido", descricao: "A criatura ensurdida não pode ouvir e automaticamente falha qualquer teste de habilidade que requeira audição."},
    {id: 9, label: "Envenenado", value: "Envenenado", descricao: "A criatura envenenada tem desvantagem em rolos de ataque e testes de habilidade."},
    {id: 10, label: "Exausto", value: "Exausto", descricao: "Exaustão é medida em seis níveis, cada um afetando a criatura de maneira cumulativa, começando com desvantagem em testes de habilidade e podendo levar até a morte no nível mais extremo."},
    {id: 11, label: "Incapacitado", value: "Incapacitado", descricao: "A criatura incapacitada não pode realizar ações ou reações."},
    {id: 12, label: "Inconsciente", value: "Inconsciente", descricao: "A criatura inconsciente está incapacitada, não pode se mover ou falar e não tem noção do seu entorno. A criatura larga tudo o que estiver segurando e cai caída."},
    {id: 13, label: "Invisível", value: "Invisível", descricao: "A criatura invisível é impossível de ver sem a ajuda de magia ou um sentido especial. Os rolos de ataque contra a criatura têm desvantagem, e os rolos de ataque da criatura têm vantagem."},
    {id: 14, label: "Paralisado", value: "Paralisado", descricao: "A criatura paralisada está incapacitada e não pode se mover ou falar, automaticamente falha em testes de resistência de Força e Destreza, e ataques contra ela têm vantagem."},
    {id: 15, label: "Petrificado", value: "Petrificado", descricao: "A criatura petrificada é transformada, juntamente com qualquer objeto não mágico que esteja carregando ou vestindo, em uma substância inanimada sólida, usualmente pedra."}
];

const tormentaCondicoes: Array<any> = [
    { id: 1, label: "Abalado", value: "Abalado", descricao: "O personagem sofre -2 em testes de perícia. Se ficar abalado novamente, em vez disso fica apavorado. Medo."},
    { id: 2, label: "Agarrado", value: "Agarrado", descricao: "O personagem fica desprevenido e imóvel, sofre -2 em testes de ataque e só pode atacar com armas leves. Ataques à distância contra um alvo envolvido em uma manobra agarrar têm 50% de chance de acertar o alvo errado. Movimento."},
    { id: 3, label: "Alquebrado", value: "Alquebrado", descricao: "O custo em pontos de mana das habilidades do personagem aumenta em +1. Mental."},
    { id: 4, label: "Apavorado", value: "Apavorado", descricao: "O personagem sofre -5 em testes de perícia e não pode se aproximar voluntariamente da fonte do medo. Medo."},
    { id: 5, label: "Atordoado", value: "Atordoado", descricao: "O personagem fica desprevenido e não pode fazer ações. Mental."},
    { id: 6, label: "Caído", value: "Caído", descricao: "O personagem sofre -5 em ataques corpo a corpo e seu deslocamento é reduzido a 1,5m. Além disso, sofre -5 na Defesa contra ataques corpo a corpo e recebe +5 na Defesa contra ataques à distância (cumulativos com outras condições)."},
    { id: 7, label: "Cego", value: "Cego", descricao: "O personagem fica desprevenido e lento, não pode fazer testes de Percepção para observar e sofre -5 em testes de perícias baseadas em Força ou Destreza. Todos os alvos de seus ataques recebem camuflagem total. Você é considerado cego enquanto estiver em uma área de escuridão total, a menos que algo lhe permita perceber no escuro. Sentidos."},
    { id: 8, label: "Confuso", value: "Confuso", descricao: "O personagem comporta-se de modo aleatório. Role 1d6 no início de seus turnos: 1) Movimenta-se em uma direção escolhida por uma rolagem de 1d8; 2-3) Não pode fazer ações, e fica balbuciando incoerentemente; 4-5) Usa a arma que estiver empunhando para atacar a criatura mais próxima, ou a si mesmo se estiver sozinho (nesse caso, apenas role o dano); 6) A condição termina e pode agir normalmente. Mental."},
    { id: 9, label: "Debilitado", value: "Debilitado", descricao: "O personagem sofre -5 em testes de Força, Destreza e Constituição e de perícias baseadas nesses atributos. Se o personagem ficar debilitado novamente, em vez disso fica inconsciente."},
    { id: 10, label: "Desprevenido", value: "Desprevenido", descricao: "O personagem sofre -5 na Defesa e em Reflexos. Você fica desprevenido contra inimigos que não possa perceber. "},
    { id: 11, label: "Doente", value: "Doente", descricao: "Sob efeito de uma doença. Metabolismo."},
    { id: 12, label: "Em Chamas", value: "Em Chamas", descricao: "O personagem está pegando fogo. No início de seus turnos, sofre 1d6 pontos de dano de fogo. O personagem pode gastar uma ação padrão para apagar o fogo com as mãos. Imersão em água também apaga as chamas."},
    { id: 13, label: "Enfeitiçado", value: "Enfeitiçado", descricao: "O personagem se torna prestativo em relação à fonte da condição. Ele não fica sob controle da fonte, mas percebe suas palavras e ações da maneira mais favorável possível. A fonte da condição recebe +10 em testes de Diplomacia com o personagem. Mental."},
    { id: 14, label: "Enjoado", value: "Enjoado", descricao: "O personagem só pode realizar uma ação padrão ou de movimento (não ambas) por rodada. Ele pode gastar uma ação padrão para fazer uma investida, mas pode avançar no máximo seu deslocamento (e não o dobro). Metabolismo. "},
    { id: 15, label: "Enredado", value: "Enredado", descricao: "O personagem fica lento, vulnerável e sofre -2 em testes de ataque. Movimento."},
    { id: 16, label: "Envenenado", value: "Envenenado", descricao: "O efeito desta condição varia de acordo com o veneno. Pode ser perda de vida recorrente ou outra condição (como fraco ou enjoado). Perda de vida recorrente por venenos é cumulativa. Veneno."},
    { id: 17, label: "Esmorecido", value: "Emorecido", descricao:  "O personagem sofre -5 em testes de Inteligência, Sabedoria e Carisma e de perícias baseadas nesses atributos. Mental."},
    { id: 18, label: "Exausto. O personagem fica debilitado, lento e vulnerável. Se ficar exausto novamente, em vez disso fica inconsciente. Cansaço."},
    { id: 19, label: "Fascinado", value: "Fascinado", descricao: "Com a atenção presa em alguma coisa. O personagem sofre -5 em Percepção e não pode fazer ações, exceto observar aquilo que o fascinou. Esta condição é anulada por ações hostis contra o personagem ou se o que o fascinou não estiver mais visível. Balançar uma criatura fascinada para tirá-la desse estado gasta uma ação padrão. Mental."},
    { id: 20, label: "Fatigado", value: "Fatigado", descricao: "O personagem fica fraco e vulnerável. Se ficar fatigado novamente, em vez disso fica exausto. Cansaço."},
    { id: 21, label: "Fraco", value: "Fraco", descricao: "O personagem sofre -2 em testes de Força, Destreza e Constituição e de perícias baseadas nesses atributos. Se ficar fraco novamente, em vez disso fica debilitado."},
    { id: 22, label: "Frustrado", value: "Frustrado", descricao: "O personagem sofre -2 em testes de Inteligência, Sabedoria e Carisma e de perícias baseadas nesses atributos. Se ficar frustrado novamente, em vez disso fica esmorecido. Mental."},
    { id: 23, label: "Imóvel", value: "Imóvel", descricao: "Imóvel. Todas as formas de deslocamento do personagem são reduzidas a 0m. Movimento."},
    { id: 24, label: "Inconsciente", value: "Inconsciente", descricao: "O personagem fica indefeso e não pode fazer ações, incluindo reações (mas ainda pode fazer testes que sejam naturalmente feitos quando se está inconsciente, como testes de Constituição para estabilizar sangramento). Balançar uma criatura para acordá-la gasta uma ação padrão."},
    { id: 25, label: "Indefeso", value: "Indefeso", descricao: "O personagem fica desprevenido, mas sofre -10 na Defesa, falha automaticamente em testes de Reflexos e pode sofrer golpes de misericórdia."}, 
    { id: 26, label: "Lento", value: "Lento", descricao: "Todas as formas de deslocamento do personagem são reduzidas à metade (arredonde para baixo para o primeiro incremento de 1,5m) e ele não pode correr ou fazer investidas. Movimento."},
    { id: 27, label: "Ofuscado", value: "Ofuscado", descricao: "O personagem sofre -2 em testes de ataque e de Percepção. Sentidos."},
    { id: 28, label: "Paralisado", value: "Paralisado", descricao: "Fica imóvel e indefeso e só pode realizar ações puramente mentais. Movimento."},
    { id: 29, label: "Pasmo", value: "Pasmo", descricao: "Não pode fazer ações. Mental."},
    { id: 30, label: "Petrificado", value: "Petrificado", descricao: "O personagem fica inconsciente e recebe redução de dano 8. Metamorfose."},
    { id: 31, label: "Sangrando", value: "Sangrando", descricao: "No início de seu turno, o personagem deve fazer um teste de Constituição (CD 15). Se falhar, perde 1d6 pontos de vida e continua sangrando. Se passar, remove essa condição. Metabolismo."},
    { id: 32, label: "Sobrecarregado", value: "Sobrecarregado", descricao: "O personagem sofre penalidade de armadura -5 e seu deslocamento é reduzido -3m. Movimento."},
    { id: 33, label: "Surdo", value: "Surdo", descricao: "O personagem não pode fazer testes de Percepção para ouvir e sofre -5 em testes de Iniciativa. Além disso, é considerado em condição ruim para lançar magias. Sentidos."},
    { id: 34, label: "Surpreendido", value: "Surpreendido", descricao: "O personagem fica desprevenido e não pode fazer ações."},
    { id: 35, label: "Vulnerável", value: "Vulnerável", descricao: "O personagem sofre -2 na Defesa."}
];

const ordemCondicoes: Array<any> = [
    {id: 1, label: "Abalado", value: "Abalado", descricao: "O personagem sofre -1 D20 em testes. Se ficar abalado novamente, em vez disso fica apavorado. Condição de medo." },
    {id: 2, label: "Agarrado", value: "Agarrado", descricao: "O personagem fica desprevenido e imóvel, sofre -1 D20 em testes de ataque e só pode atacar com armas leves. Um personagem fazendo um ataque à distância contra um alvo envolvido na manobra agarrar tem 50% de chance de acertar o alvo errado. Condição de paralisia." },
    {id: 3, label: "Alquebrado", value: "Alquebrado", descricao: "O custo em pontos de esforço das habilidades e dos rituais do personagem aumenta em +1. Condição mental." },
    {id: 4, label: "Apavorado", value: "Apavorado", descricao: "O personagem sofre -2 D20 em testes de perícia e deve fugir da fonte do medo da maneira mais eficiente possível (mas pode parar de fazê-lo assim que a perder de vista ou se afastar mais do que alcance médio). Se não puder, poderá agir, mas não poderá se aproximar voluntariamente da fonte do medo. Condição de medo." },
    {id: 5, label: "Asfixiado", value: "Asfixiado", descricao: "O personagem não pode respirar. Um personagem asfixiado pode prender seu fôlego por um total de rodadas igual ao seu Vigor e, a cada vez que sofre dano enquanto está nesta condição, reduz este valor em 1. Ao final de seu turno na última dessas rodadas, o personagem fica morrendo." },
    {id: 6, label: "Atordoado", value: "Atordoado", descricao: "O personagem fica desprevenido e não pode fazer ações. Condição mental." },
    {id: 7, label: "Caído", value: "Caído", descricao: "Deitado no chão. O personagem sofre -2 D20 em ataques corpo a corpo e seu deslocamento é reduzido a 1,5m. Além disso, sofre -5 na Defesa contra ataques corpo a corpo, mas recebe +5 na Defesa contra ataques à distância." },
    {id: 8, label: "Cego", value: "Cego", descricao: "O personagem fica desprevenido e lento, não pode fazer testes de Percepção para observar e sofre -2 D20 em testes de perícias baseadas em Agilidade ou Força. Todos os alvos de seus ataques recebem camuflagem total. Você é considerado cego enquanto estiver em uma área de escuridão total, a menos que algo lhe permita perceber no escuro. Condição de sentidos." },
    {id: 9, label: "Confuso", value: "Confuso", descricao: "O personagem comporta-se de modo aleatório. Role 1d6 no início de seus turnos: 1) Movimenta-se em uma direção escolhida por uma rolagem de 1d8; 2-3) Não pode fazer ações e fica balbuciando incoerentemente; 4-5) Usa a arma que estiver empunhando para atacar o ser mais próximo, ou a si mesmo se estiver sozinho (nesse caso, apenas role o dano); 6) A condição termina e pode agir normalmente. Condição mental." },
    {id: 10, label: "Debilitado", value: "Debilitado", descricao: "O personagem sofre -2 D20 em testes de Agilidade, Força e Vigor. Se o personagem ficar debilitado novamente, em vez disso fica inconsciente." },
    {id: 11, label: "Desprevenido", value: "Desprevenido", descricao: "Despreparado para reagir. O personagem sofre -5 na Defesa e -1 D20 em Reflexos. Você fica desprevenido contra inimigos que não possa perceber."},
    {id: 12, label: "Doente", value: "Doente", descricao: "Sob efeito de uma doença." },
    {id: 13, label: "Em Chama", value: "Em Chamas", descricao: "O personagem está pegando fogo. No início de seus turnos, sofre 1d6 pontos de dano de fogo. O personagem pode gastar uma ação padrão para apagar o fogo com as mãos. Imersão em água também apaga as chamas." },
    {id: 14, label: "Enjoado", value: "Enjoado", descricao: "O personagem só pode realizar uma ação padrão ou de movimento (não ambas) por rodada." },
    {id: 15, label: "Enredado", value: "Enredado", descricao: "O personagem fica lento, vulnerável e sofre -1 D20 em testes de ataque. Condição de paralisia." },
    {id: 16, label: "Envenenado", value: "Envenenado", descricao: "O efeito desta condição varia de acordo com o veneno. Pode ser outra condição (por exemplo, fraco ou enjoado) ou dano recorrente (por exemplo, 1d12 pontos de dano de veneno por rodada). A descrição do veneno determina a duração dele (caso nada seja dito, a condição dura pela cena). Dano recorrente de condições envenenado sempre se acumula (mesmo se as condições ou fontes que as causam forem iguais)." },
    {id: 17, label: "Esmorecido", value: "Esmorecido", descricao: "O personagem sofre -2 D20 em testes de Intelecto e Presença. Condição mental." },
    {id: 18, label: "Exausto", value: "Exausto", descricao: "O personagem fica debilitado, lento e vulnerável. Se ficar exausto novamente, em vez disso fica inconsciente. Condição de fadiga." },
    {id: 19, label: "Fascinado", value: "Fascinado", descricao: "Com a atenção presa em alguma coisa. O personagem sofre -2 D20 em Percepção e não pode fazer ações, exceto observar aquilo que o fascinou. Qualquer ação hostil contra o personagem anula esta condição. Balançar um ser fascinado para tirá-lo desseestado gasta uma ação padrão. Condição mental." },
    {id: 20, label: "Fatigado", value: "Fatigado", descricao: "O personagem fica fraco e vulnerável. Se o personagem ficar fatigado novamente, em vez disso fica exausto. Condição de fadiga." },
    {id: 21, label: "Fraco", value: "Fraco", descricao: "O personagem sofre -1 D20 em testes de Agilidade, Físico e Vigor. Se ficar fraco novamente, em vez disso fica debilitado." },
    {id: 22, label: "Frustrado", value: "Frustrado", descricao: "O personagem sofre -1 D20 em testes de Intelecto e Presença. Se ficar frustrado novamente,em vez disso fica esmorecido. Condição mental." },
    {id: 23, label: "Imóvel", value: "Imóvel", descricao: "Todas as formas de deslocamento do personagem são reduzidas a 0m. Condição de paralisia." },
    {id: 24, label: "Inconsciente", value: "Inconsciente", descricao: "O personagem fica indefeso e não pode fazer ações, incluindo reações. Balançar um ser para acordá-lo gasta uma ação padrão." },
    {id: 25, label: "Indefeso", value: "Indefeso", descricao: "O personagem é considerado desprevenido, mas sofre -10 na Defesa, falha automaticamente em testes de Reflexos e pode sofrer golpes de  misericórdia." },
    {id: 26, label: "Lento", value: "Lento", descricao: "Todas as formas de deslocamento do personagem são reduzidas à metade (arredonde para baixo  para o primeiro incremento de 1,5m) e ele não pode  correr ou fazer investidas. Condição de paralisia." },
    {id: 27, label: "Machucado", value: "Machucado", descricao: "O personagem tem menos da metade de seus pontos de vida totais." },
    {id: 28, label: "Morrendo", value: "Morrendo", descricao: "Com 0 pontos de vida. Um personagem morrendo fica inconsciente e, se terminar mais de três rodadas (não necessariamente consecutivas) morrendo na mesma cena, morre. Esta condição se encerra se o personagem voltar a ter pelo menos 1 PV." },
    {id: 29, label: "Ofuscado", value: "Ofuscado", descricao: "O personagem sofre -1 D20 em testes de ataque e de Percepção. Condição de sentidos."},
    {id: 30, label: "Paralisado", value: "Paralisado", descricao: "O personagem fica imóvel e indefeso e só pode realizar ações puramente mentais. Condição de paralisia." },
    {id: 31, label: "Pasmo", value: "Pasmo", descricao: "O personagem não pode fazer ações. Condição mental."},
    {id: 32, label: "Petrificado", value: "Petrificado", descricao: "O personagem fica inconsciente e recebe resistência a dano 10." },
    {id: 33, label: "Sangrando", value: "Sangrando", descricao: "Com um ferimento aberto. No início de seus turnos, o personagem deve fazer um teste de Vigor (DT 20). Se passar, estabiliza e remove essa condição. Se falhar, perde 1d6 pontos de vida e continua sangrando." },
    {id: 34, label: "Surdo", value: "Surdo", descricao: "O personagem não pode fazer testes de Percepção para ouvir e sofre -2 D20 em testes de Iniciativa. Além disso, é considerado em condição ruim para lançar rituais. Condição de sentidos."},
    {id: 35, label: "Surpreendido", value: "Surpreendido", descricao:"Surpreendido. Não ciente de seus inimigos. O personagem fica desprevenido e não pode fazer ações." },
    {id: 36, label: "Vulnerável", value: "Vulnerável", descricao: "O personagem sofre -5 na Defesa" }
];

export const sistemas: Array<Sistema> = [
    {id: 1, nome: "Ordem Paranormal", imagem: OrdemCapa, condicoes: ordemCondicoes},
    {id: 2, nome: "Tormenta 20", imagem: TormentaCapa, condicoes: tormentaCondicoes},
    {id: 3, nome: "D&D", imagem: DedCapa, condicoes: dedCondicoes},
    {id: 4, nome: "Call Of Cthullu", imagem: CallCapa, condicoes: ordemCondicoes},
]
